 'use strict';
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs/promises');let browser,stage='start';process.on('SIGINT',()=>browser?.close().finally(()=>process.exit(130)));
(async()=>{const input=JSON.parse(await fs.readFile(process.env.WEB_FILE_INPUT,'utf8'));browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE});try{const context=await browser.newContext({ignoreHTTPSErrors:true}),page=await context.newPage();await page.addInitScript(()=>{window.blobCreated=0;window.blobRevoked=0;const create=URL.createObjectURL,revoke=URL.revokeObjectURL;URL.createObjectURL=function(...args){window.blobCreated++;return create.apply(this,args);};URL.revokeObjectURL=function(...args){window.blobRevoked++;return revoke.apply(this,args);};});
 const login=async()=>{await page.goto(input.baseURL+'/web/');await page.getByRole('button',{name:/使用企业账号登录/}).click();await page.locator('#workspace').waitFor({state:'visible'});await page.locator('#identity-options .identity-button').first().click();await page.locator('.conversation-button').first().click();await page.locator('#file-controls').waitFor({state:'visible'});};
 const logout=async()=>{if(await page.locator('#message-search-dialog').evaluate(e=>e.open))await page.locator('#message-search-close').click();await page.locator('#logout-button').click();await page.locator('#workspace').waitFor({state:'hidden'});assert.equal(await page.locator('[data-file-save]').count(),0);assert.equal(await page.locator('#messages').getByText(input.name,{exact:true}).count(),0);};
 const select=async()=>{await page.locator('#file-select').setInputFiles({name:input.sample.name,mimeType:input.sample.mime,buffer:await fs.readFile(input.sample.path)});await page.waitForFunction(()=>!document.getElementById('file-upload').disabled);};
 const facts={};for(const point of ['reserve','PUT','scan','ACK','search']){
  stage=point;await login();let release,reachedResolve;const reached=new Promise(r=>reachedResolve=r),hold=new Promise(r=>release=r);let held=false;
  const match=r=>{const p=new URL(r.url()).pathname,m=r.method();return point==='reserve'?m==='POST'&&p.endsWith('/files'):point==='PUT'?m==='PUT'&&p.endsWith('/content'):point==='scan'?m==='GET'&&/^\/api\/v1\/files\/[a-f0-9-]+$/.test(p):point==='ACK'?m==='POST'&&p.endsWith('/messages'):m==='GET'&&p.endsWith('/files/search');};
  const routeHandler=async route=>{if(held || !match(route.request()))return route.continue();held=true;const response=await route.fetch();assert([200,201].includes(response.status()));reachedResolve();await hold;await route.fulfill({response}).catch(()=>{});};await page.route('**/api/v1/**',routeHandler);
  if(point==='search'){await page.locator('#message-search-open').click();await page.locator('#message-search-mode').selectOption('file');await page.locator('#message-search-query').fill('上下文');await page.locator('#message-search-apply').click();}
  else{await select();await page.locator('#file-upload').click();if(point==='ACK'){await page.waitForFunction(()=>document.getElementById('file-status').textContent.includes('扫描通过'));await page.locator('#send-button').click();}}
  await Promise.race([reached,new Promise((_,reject)=>setTimeout(()=>reject(new Error('boundary not reached')),20000))]);await logout();release();await page.unroute('**/api/v1/**',routeHandler);await page.evaluate(()=>new Promise(requestAnimationFrame));assert.equal(await page.locator('#message-search-list li').count(),0);assert.equal(await page.locator('#messages').getByText(input.sample.name,{exact:true}).count(),0);assert.equal(await page.locator('[data-file-save]').count(),0);await page.getByRole('button',{name:/使用企业账号登录/}).click();await page.locator('#workspace').waitFor({state:'visible'});assert.equal(await page.locator('#messages').getByText(input.sample.name,{exact:true}).count(),0);await logout();facts[point+'_logout_no_late_refill']=true;
 }
 stage='actual read';await login();await context.request.get(input.baseURL+'/__p425/read-arm');const partialResponse=page.waitForResponse(r=>new URL(r.url()).pathname.endsWith('/content')&&r.request().method()==='GET');await page.getByRole('button',{name:'请求下载',exact:true}).first().click();assert.equal((await partialResponse).status(),200);await page.waitForFunction(async()=>{const r=await fetch('/__p425/read-state',{cache:'no-store'});return (await r.json()).reached;});await logout();assert.equal(await page.evaluate(()=>window.blobCreated),0);facts.real_partial_read_abort=true;
 stage='Blob release';await login();for(let attempt=0;attempt<3;attempt++){await page.getByRole('button',{name:'请求下载',exact:true}).first().click();await page.waitForFunction(()=>document.querySelector('[data-file-save]') || document.getElementById('file-save').textContent.includes('下载未完成'));if(await page.locator('[data-file-save]').count())break;}
 await page.locator('[data-file-save]').waitFor();assert.equal(await page.evaluate(()=>window.blobCreated),1);await logout();assert.equal(await page.evaluate(()=>window.blobRevoked),1);facts.Blob_logout_revoked=true;await context.close();console.log(JSON.stringify(facts));}finally{await browser.close();}})().catch(()=>{console.error('real context browser failed at '+stage);process.exitCode=1;});
