'use strict';const assert=require('node:assert/strict'),{environment}=require('./file_unit_helpers.cjs');
const env=environment('file-policy'),{window,document}=env;const el=id=>document.getElementById('file-policy-'+id);
const id='22222222-2222-4222-8222-222222222222';let ctx={identityKey:'admin',membershipId:id,identityEpoch:1,conversation:id,conversationEpoch:1,kind:'direct'},kind='upload',writes=[],conflict=false,unknown=false,hold=null,cursor='',history=[];
let upload={enabled:true,max_size_bytes:'26214400',allowed_media_types:['application/pdf','image/png','image/jpeg','text/plain'],upload_ttl_seconds:'900',tenant_storage_budget_bytes:'1073741824',version:'9007199254740993',approval_reference:'REF',actor_user_id:id,acting_membership_id:id,updated_at:new Date().toISOString()},retention={file_retention_days:'365',cleanup_enabled:false,version:'0',approval_reference:'',actor_user_id:'',acting_membership_id:'',current_policy_applies_to_existing_files:true};
const request=async(p,o={})=>{kind=p.includes('upload')?'upload':'retention';if(o.method==='PUT'){const b=JSON.parse(o.body);writes.push(b);if(conflict){const e=new Error('conflict');e.status=409;throw e}if(unknown)throw new Error('unknown');if(kind==='upload')upload={...upload,...b,version:String(BigInt(b.expected_version)+1n)};else retention={...retention,...b,version:String(BigInt(b.expected_version)+1n),actor_user_id:id,acting_membership_id:id,updated_at:new Date().toISOString()};return kind==='upload'?upload:retention}if(hold)return new Promise(resolve=>hold=resolve);if(p.includes('/history'))return {history,next_cursor:cursor};return kind==='upload'?upload:retention};
const flow=new window.FilePolicy({request,context:()=>({...ctx}),canOpen:()=>true});
const review=()=>{el('reference').value='APPROVAL-1';el('review').click();el('confirm').checked=true};
(async()=>{
 await flow.open('upload');assert(el('current').textContent.includes('9007199254740993'));el('reference').value='';await assert.rejects(flow.save());assert.equal(writes.length,0);
 el('size').value='0.000001';review();await assert.rejects(flow.save());assert.equal(writes.length,0);el('size').value='25';el('budget').value='1024.000000001';review();await assert.rejects(flow.save());el('budget').value='1';
 for(const v of ['59','3601']){el('ttl').value=v;review();await assert.rejects(flow.save())}el('ttl').value='900';review();await flow.save();assert.equal(writes[0].expected_version,'9007199254740993');assert.equal(writes[0].max_size_bytes,'26214400');
 await flow.open('upload');conflict=true;review();await assert.rejects(flow.save());const count=writes.length;await assert.rejects(flow.save());assert.equal(writes.length,count);conflict=false;await flow.open('upload');unknown=true;review();await assert.rejects(flow.save());const count2=writes.length;await assert.rejects(flow.save());assert.equal(writes.length,count2);unknown=false;await flow.open('upload');
 await flow.open('retention');for(const v of ['0','3651']){el('days').value=v;review();await assert.rejects(flow.save())}el('days').value='30';el('cleanup').checked=true;review();await flow.save();assert.equal(writes.at(-1).cleanup_enabled,true);
 cursor='same';await assert.rejects(flow.loadHistory(true));cursor='';await flow.open('upload');history=Array.from({length:20},(_,i)=>({...upload,version:String(BigInt(upload.version)-BigInt(i))}));cursor='same';await flow.loadHistory(true);assert(el('history').textContent.includes('9007199254740994'));await assert.rejects(flow.loadHistory(false));history=[];cursor='';hold=true;const waiting=flow.open('upload');await env.flush();ctx.identityEpoch++;flow.contextChanged();hold(upload);hold=null;try{await waiting}catch(_){}assert.equal(el('current').textContent,'');assert.equal(el('history').textContent,'');assert.equal(el('dialog').open,false);
 console.log('filePolicyExactDecimal, filePolicyCASConflict, filePolicyUnknownResult, filePolicyIdentitySwitch, filePolicyHistoryProgress: PASS');
})().catch(e=>{console.error(e);process.exitCode=1});
