'use strict';
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs/promises');let browser,stage='start';
process.on('SIGINT',()=>{browser?.close().finally(()=>process.exit(130));});
(async()=>{const input=JSON.parse(await fs.readFile(process.env.WEB_FILE_INPUT,'utf8'));browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE});try{const context=await browser.newContext({ignoreHTTPSErrors:true}),page=await context.newPage();stage='PKCE';await page.goto(input.baseURL+'/web/');await page.getByRole('button',{name:/使用企业账号登录/}).click();await page.locator('#workspace').waitFor({state:'visible',timeout:15000});await page.locator('#identity-options .identity-button').first().click();await page.locator('.conversation-button').first().click();stage='upload settings';await page.locator('#file-policy-upload-open').waitFor({state:'visible',timeout:15000});await page.locator('#file-policy-upload-open').click();await page.waitForFunction(()=>!document.getElementById('file-policy-review').disabled);if(input.conflict){
 assert((await page.locator('#file-policy-current').textContent()).includes('版本：9007199254740993'));const bodies=[];
 const review=async reference=>{await page.locator('#file-policy-reference').fill(reference);await page.locator('#file-policy-review').click();await page.locator('#file-policy-confirm').check();};
 await page.route('**/api/v1/admin/file-upload-policy',async route=>{if(route.request().method()!=='PUT')return route.continue();bodies.push(JSON.parse(route.request().postData()));const response=await route.fetch();if(bodies.length===1){assert.equal(response.status(),409);await route.fulfill({response});}else{assert.equal(response.status(),200);await route.abort('failed');}});
 stage='real concurrent CAS';await review('P425-FIRST-APPROVED');await page.locator('#file-policy-save').click();await page.locator('#file-policy-hint').filter({hasText:'版本冲突'}).waitFor();assert.equal(await page.locator('#file-policy-save').isDisabled(),true);assert.equal(bodies.length,1);
 await page.locator('#file-policy-reload').click();await page.waitForFunction(()=>!document.getElementById('file-policy-review').disabled);assert((await page.locator('#file-policy-current').textContent()).includes('版本：9007199254740994'));assert((await page.locator('#file-policy-history').textContent()).includes('P425-CONCURRENT-APPROVED'));
 stage='unknown saved CAS';await review('P425-SECOND-APPROVED');await page.locator('#file-policy-save').click();await page.locator('#file-policy-hint').filter({hasText:'结果待确认'}).waitFor();assert.equal(await page.locator('#file-policy-save').isDisabled(),true);assert.equal(bodies.length,2);
 await page.locator('#file-policy-reload').click();await page.waitForFunction(()=>!document.getElementById('file-policy-review').disabled);assert((await page.locator('#file-policy-current').textContent()).includes('版本：9007199254740995'));assert.equal(await page.locator('#file-policy-history li').count(),2);assert.deepEqual(bodies.map(b=>b.expected_version),['9007199254740993','9007199254740994']);await context.close();console.log(JSON.stringify({real_concurrent_CAS:true,exact_large_version:true,unknown_write_readback:true,no_auto_overwrite:true}));return;
 }assert((await page.locator('#file-policy-current').textContent()).includes('版本：1'));await page.locator('#file-policy-close').click();stage='retention settings';await page.locator('#file-policy-retention-open').click();await page.waitForFunction(()=>!document.getElementById('file-policy-review').disabled);await page.locator('#file-policy-days').fill('30');await page.locator('#file-policy-reference').fill('P425-RETENTION-APPROVED');await page.locator('#file-policy-review').click();const review=await page.locator('#file-policy-preview').textContent();assert(review.includes('365'));assert(review.includes('30'));assert(review.includes('P425-RETENTION-APPROVED'));await page.locator('#file-policy-confirm').check();await page.locator('#file-policy-save').click();await page.locator('#file-policy-hint').filter({hasText:'配置已保存'}).waitFor({timeout:15000});assert((await page.locator('#file-policy-history').textContent()).includes('P425-RETENTION-APPROVED'));assert((await page.locator('#file-policy-current').textContent()).includes('版本：1'));await context.close();console.log(JSON.stringify({real_CAS:true,exact_version:true,approval_review:true,immutable_history:true,no_cleanup_command:true}));}finally{await browser.close();}})().catch(()=>{console.error('real settings browser failed at '+stage);process.exitCode=1;});
